djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import landing_page, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name="landing-page"),
    path('leads/', include('leads.urls', namespace="leads")),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', SignupView.as_view(), name="signup"),
]

if settings.DEBUG:
  urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  

leads/urls.py
from django.urls import path
from .views import LeadListView, LeadDetailView

from .views import lead_list, lead_detail, lead_create, lead_update, lead_delete, lead_review


app_name= "leads"


urlpatterns = [
  path('', LeadListView.as_view(), name="lead-list"),
  path('<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
  path('<int:pk>/update/', lead_update, name="lead-update"),
  path('<int:pk>/delete/', lead_delete, name="lead-delete"),
  path('create/', lead_create, name="lead-create"),
  path('reviews/', lead_review, name="lead-review"),
  
  
  
]

leads/models.py
from django.db import models 
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
  pass


class lead(models.Model):
  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  age = models.IntegerField(default=0)
  agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

  def __str__(self):
   return f"{self.first_name} {self.last_name}"
  
 
  
  

class Agent(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  
  def __str__(self):
   return self.user.email

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import lead

User = get_user_model()

class LeadModelForm(forms.ModelForm):
  class Meta:
    model = lead
    fields = (
      'first_name',
      'last_name',
      'age',
      'agent',
    )




class LeadForm(forms.Form):
  first_name = forms.CharField() 
  last_name = forms.CharField()
  age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
  class Meta:
    model = User
    fields = ("username",)
    field_classes = {'username': UsernameField}

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render , redirect, reverse
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView , DetailView, CreateView, UpdateView
from .models import lead, Agent
from .forms import LeadForm , LeadModelForm, CustomUserCreationForm
from django.views import generic
#from django.contrib.auth.forms import UserCreationForm

class SignupView(generic.CreateView):
   template_name="registration/signup.html"
   form_class = CustomUserCreationForm
   
   def get_success_url(self):
      return "/login"


def landing_page(request):
   return render(request, "landing.html")


#classview example

class LeadListView(ListView):
   template_name="leads/lead_list.html"
   queryset = lead.objects.all() #here in function we need to create dictionary context but queryset is a defualt  context with name object_name.
   


def lead_list(request):
  leads = lead.objects.all()
  #leads is now a list of data querysets
  context = {
    "leads": leads
  }
  print(context)
  #how to understand the dictionary logic and visuallise it?
  return render(request, "leads/lead_list.html" , context)

class LeadDetailView(DetailView):
   template_name="leads/lead_details.html"
   queryset = lead.objects.all() #here in function we need to create dictionary context but queryset is a defualt  context with name object_name.
   context_object_name = "lead"

def lead_detail(request, pk):
    print(pk)
    Lead = lead.objects.get(id=pk)
    #there is alead confusion
    context = {
       "lead": Lead
    }
    
    return render(request, "leads/lead_details.html", context)  

class LeadCreateView(CreateView):
   template_name="leads/lead_create.html"
   form_class = LeadModelForm
   
   def get_success_url(self):
      return "/leads"
   
   def form_valid(self):
      # TODO send email
      send_mail(
         subject="A lead has been created",
         message="Go to the site to see the new lead",
         from_email= ["test2@test.com"]
      )
      return super(LeadCreateView, self).form_valid(form)





def lead_create(request):
   form = LeadModelForm()
   #first setting form empty by leaving leadform empty
   if request.method == "POST":
      print('Receoving a post request')
      form = LeadModelForm(request.POST)
      if form.is_valid():
         #first_name = form.cleaned_data['first_name']
         #last_name = form.cleaned_data['last_name']
         #age = form.cleaned_data['age']
         #agent = form.cleaned_data['agent']
         #lead.objects.create(
         #   first_name= first_name,
         #   last_name = last_name,
         #   age = age,
         #   agent = agent
         #)
         form.save()
         #form.save does the exact thing as above lines
          
         print("The lead has been created")

         return redirect("/leads")
         

   context={
      "form": form
   }
   return render(request, "leads/lead_create.html", context)


def lead_update(request, pk):
   Lead = lead.objects.get(id = pk)
   form = LeadModelForm(instance=Lead)
   if request.method == "POST":
      form = LeadModelForm(request.POST, instance=Lead)
      if form.is_valid():
         form.save()
         return redirect("/leads")
   context = {
      "form": form,
      "lead": Lead
     }
   return render (request, "leads/lead_update.html", context)




def lead_delete(request, pk):
   Lead = lead.objects.get(id = pk)
   Lead.delete()
   return redirect("/leads")



# def lead_update(request, pk):
#     Lead = lead.objects.get(id=pk)
#     form = LeadForm()
#    #first setting form empty by leaving leadform empty
#     if request.method == "POST":
#       form = LeadForm(request.POST)
#       if form.is_valid():
#          first_name = form.cleaned_data['first_name']
#          last_name = form.cleaned_data['last_name']
#          age = form.cleaned_data['age']
#          Lead.first_name = first_name
#          Lead.last_name = last_name
#          Lead.age = age
#          Lead.save()
#          #form.save does the exact thing as above lines
#          return redirect("/leads")
   
#     context = {
#       "form": form,
#       "lead": Lead
#     }
#     return render (request, "leads/lead_update.html", context)


def lead_review(request):

   leads = lead.objects.all()
   #leads is now a list of data querysets
   context = {
    "leads": leads
   } 
   return render (request, "leads/lead_review.html", context)

leads/templates/leads/lead_create.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
  <h1>create a new lead</h1>
  <form method="post">
  {% csrf_token %}
  #action sends 
  {{ form.as_p }}
  <button type="submit">Submit</submit>
  </form>
	    
  </body>
</html>

{% endblock content %}

leads/templates/leads/lead_details.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{ lead.first_name}} {{ lead.last_name }} </h1>
        <div class="flex mb-4">
         <a href="{% url 'leads:lead-detail' lead.pk %} " class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Overview
              </a>
         <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Reviews
              </a>
         <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Dummy location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell Phone</span>
          <span class="ml-auto text-gray-900">4115121545</span>
        </div>
        <div class="flex">
          
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
    <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
  <h1>This is the details of {{ lead.first_name }}</h1>
  <p> The persons age is: {{ lead.age }} </p>
  <p>The agent responsible for teh led is {{ lead.agent }}</p>

  <hr/>
  <a href= "{% url 'leads:lead-update' lead.pk %}">Update</a>
  <a href= "{% url 'leads:lead-delete' lead.pk %}">Delete</a>


{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
          <h1 class="text-4xl text-gray-800">Leads</h1>
        </div>
        
      
        <div>
          <a class="text-gray-500 hover:text-blue-500" href= "{% url 'leads:lead-create' %}"> Create a new lead </a>
        </div>
      </div>    


     <hr />
    <div class="flex flex-wrap -m-4">
       {% for lead in object_list %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
            {{ lead.first_name }} {{ lead.last_name }}
            </h2>
            <p class="leading-relaxed text-base">
            Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'leads:lead-detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
            View this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">The Catalyzer</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</section>

  
  

{% endblock content %}

	

leads/templates/leads/lead_review.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{ lead.first_name}} {{ lead.last_name }} </h1>
        <div class="flex mb-4">
         <a href="{% url 'leads:lead-detail' lead.pk %} " class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Overview
              </a>
         <a href="#" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Tasks
              </a>
         <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Edit Details</a>
        </div>
        <p class="leading-relaxed mb-4"> 
        Name : {{ lead.first_name }} {{ lead.last_name }}
        <br>
        Age : {{ lead.age }}
        <br> 
        <h5>Records:</h5>
        <hr/>
        A consistent Consumer of our services.
        In Future might Stop using our services.
         <br>
        </p>
        
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
    <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
  <h1>This is the details of {{ lead.first_name }}</h1>
  <p> The persons age is: {{ lead.age }} </p>
  <p>The agent responsible for teh led is {{ lead.agent }}</p>

  <hr/>
  <a href= "{% url 'leads:lead-update' lead.pk %}">Update</a>
  <a href= "{% url 'leads:lead-delete' lead.pk %}">Delete</a>


{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}



{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{ lead.first_name}} {{ lead.last_name }} </h1>
          <div class="flex mb-4">
              <a href="{% url 'leads:lead-detail' lead.pk %} " class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Overview
              </a>
              <a href="#" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Review
              </a>
              <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Edit Details</a>
          </div>

          <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Submit</submit>
          </form>
          
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
   


{% endblock content %}

leads/templates/leads/second_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HTML 5 Boilerplate</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
  <h1>Hello world</h1>
  <p> This is the second page</p>

  <ul>
  
  {% for lead in leads %}
  <li>
  {{ lead }}
  </li>
  {% endfor %}
  </ul>

 
  </body>
</html>

templates/base.html
{% load static %}




<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>djcrm</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">

    <link hred = "{% static '/static/css/styles.css' %}" rel="stylesheet">
    
    <script src="https://cdn.tailwindcss.com"></script>
     
 
     
 
  </head>
  <body>

    <div class="max-w-4xl mx-auto bg-gray-100">
      {% include "navbar.html" %}
      {% block content %}
      {% endblock content %}

    </div>

    

   
    {% include "scripts.html" %}
  
  </body>
</html>

templates/landing.html
{% extends 'base.html'%}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://www.flaticon.com/free-icon/crm_906341">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
      Maintain your CRM
      </h1>
      <p class="mb-8 leading-relaxed">
      This CRM helps you manage your work
      </p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">

        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <a href = "/leads"
      <span class="ml-3 text-xl">CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href = "{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      {% if not request.user.is_authenticated %}

      <a href='{% url 'signup' %}' class="mr-5 hover:text-gray-900">Signup</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
    logged in as: {{ request.user.username }}
      <a href='{% url 'logout' %}' class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% else %}
    <a href='{% url 'login' %}' class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
    Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
<script>

  console.log("hello")

</script>